#Create a lambda function to start, stop and terminate a running EC2 instance. Also, verify the logs generated by the lambda in the Cloudwatch 
#logs to check whether the lambda execution is done properly.

import boto3

region = 'ap-south-1'
instances = ['i-08e01d9040b1b5d1b']

ec2 = boto3.client('ec2', region_name=region)

def lambda_handler(event, context):
    
    #Start EC2 Instance
    ec2.start_instances(InstanceIds=instances)
    print('started your instance: ' + str(instances))
    
    
    #Stop EC2 Instance
    ec2.stop_instances(InstanceIds=instances)
    print('stopped your instance: ' + str(instances))

    #terminate EC2 Instance
    ec2.terminate_instances(InstanceIds=instances)
    print('Terminated your instance: ' + str(instances))
